version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: pwdDocker
      MYSQL_USER: userDocker
      MYSQL_PASSWORD: pwdDocker
      MYSQL_DATABASE: dockerDB
    ports:
      - "3308:3306"
    networks:
      - my-network
networks:
    my-network:
        driver: bridge
